-- Migration: Add session_serial to license_sessions
-- Date: 2026-01-02
-- Purpose: Enforce strict single-session usage by tracking client-side serial

ALTER TABLE license_sessions
ADD COLUMN IF NOT EXISTS session_serial VARCHAR(100);

COMMENT ON COLUMN license_sessions.session_serial IS 'Unique random serial generated by client for each process run';
