-- Create banned_devices table
create table public.banned_devices (
  id bigint generated by default as identity primary key,
  device_id text not null,
  license_key text, -- Optional: link to a license
  reason text,
  banned_by text, -- 'admin' or user email
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Add index for fast lookups
create index idx_banned_devices_device_id on public.banned_devices(device_id);
create index idx_banned_devices_license_key on public.banned_devices(license_key);

-- Enable RLS
alter table public.banned_devices enable row level security;

-- Policies
-- Admins can do everything
create policy "Admins can view all banned devices"
  on public.banned_devices for select
  using ( auth.email() like '%@signaltradingbots.com' ); -- Simplified admin check, adjust as needed or use role

create policy "Admins can insert banned devices"
  on public.banned_devices for insert
  with check ( auth.email() like '%@signaltradingbots.com' );

create policy "Admins can delete banned devices"
  on public.banned_devices for delete
  using ( auth.email() like '%@signaltradingbots.com' );
